import dj_database_url
import os

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-071_)8s3o88@im#9rvk^q=9h4#_!ck2td-7*ze*$7t3e1bn#6o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bodega', # <--- Fundamental para que Django encuentre tus modelos
    'corsheaders', # <-- Inyectar aquí obligatoriamente
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # 🔥 PRIMERA LÍNEA OBLIGATORIA: Procesa CORS antes que cualquier otra regla
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


#
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# =====================================================================
# 🔐 CONFIGURACIÓN DE SEGURIDAD CORS PARA COMPORTAMIENTO SAAS (APIO POS)
# =====================================================================
# Permite que tu frontend de Vite extraiga datos de Postgres en desarrollo
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # 🎯 EL CABLE MAESTRO: Dale acceso al nuevo puerto local de Vite
    "http://127.0.0.1:5174",  # 🛡️ Cobertura total para evitar bloqueos por CORS en tu PC
]

# Blindaje de producción: Si el sistema corre en Railway, permite que acepte peticiones de cualquier subdominio
if os.environ.get('RAILWAY_ENVIRONMENT'):
    CORS_ALLOW_ALL_ORIGINS = True

# =========================================================================
# 🎯 ARQUITECTURA DE DATOS CLOUD SE_GU_RA (SOTO SYSTEM 2026)
# =========================================================================
import dj_database_url
import os

if os.environ.get('RAILWAY_ENVIRONMENT') or os.environ.get('DATABASE_URL'):
    print("☁️ [SOTO CORE]: Conexión Cloud Activa. Extrayendo tubería de datos de Railway...")
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=False
        )
    }
else:
    print("🔒 [SOTO CORE]: Ejecución Offline. Activando SQLite3 interno...")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

