# Generated by Django 6.0.6 on 2026-08-04 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente por QR'), ('PROCESADA', 'Procesada por Daniela'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('operador', models.CharField(default='Cajero_Generico', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_bcv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_qr', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='bodega.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.producto')),
            ],
        ),
    ]
