# Generated by Django 6.0.6 on 2026-08-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cliente', models.CharField(default='Cliente Minorista (Vecino Diario)', max_length=100)),
                ('registrado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
