# Generated by Django 6.0.6 on 2026-08-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='Apio Store C.A.', max_length=150)),
                ('rif', models.CharField(default='J-12345678-0', max_length=30)),
                ('telefono', models.CharField(default='0414-1234567', max_length=50)),
                ('ciudad', models.CharField(default='Chivacoa', max_length=100)),
                ('estado', models.CharField(default='Yaracuy', max_length=100)),
                ('moneda_base', models.CharField(default='USD', max_length=10)),
            ],
        ),
    ]
