# Generated by Django 6.0.6 on 2026-08-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_configuracionnegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('glosa', models.CharField(max_length=255)),
                ('cuenta_debe', models.CharField(default='1.1.01 - Caja General', max_length=100)),
                ('cuenta_haber', models.CharField(default='4.1.01 - Ingresos por Venta', max_length=100)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('operador', models.CharField(default='Gabriel - Administrador Central', max_length=100)),
                ('cliente_identificacion', models.CharField(default='V-99999999 (Consumidor Final)', max_length=50)),
                ('tasa_bcv', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulos_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_contable', models.CharField(max_length=100)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_mayor', to='bodega.asientodiario')),
            ],
        ),
    ]
