# Generated by Django 6.0.6 on 2026-08-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_asientodiario_transaccionfactura_movimientomayor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientomayor',
            name='asiento',
        ),
        migrations.AddField(
            model_name='transaccionfactura',
            name='metodo_pago',
            field=models.CharField(default='BIOPAGO', max_length=20),
        ),
        migrations.AddField(
            model_name='transaccionfactura',
            name='productos_despachados',
            field=models.TextField(default='Mercancía General'),
        ),
        migrations.AddField(
            model_name='transaccionfactura',
            name='total_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaccionfactura',
            name='articulos_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='transaccionfactura',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaccionfactura',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='AsientoDiario',
        ),
        migrations.DeleteModel(
            name='MovimientoMayor',
        ),
    ]
