# Generated by Django 6.0.6 on 2026-08-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_remove_movimientomayor_asiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='capture_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='capture_recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('PUNTO', 'Punto de Venta'), ('BIOPAGO', 'Biopago BDV'), ('CASHEA', 'Cashea'), ('PAGO_MOVIL_QR', 'Pago Móvil Mayorista QR')], default='PUNTO', max_length=20),
        ),
    ]
