# Generated by Django 6.0.6 on 2026-08-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_factura_capture_base64_factura_capture_recibido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='articulos_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente_identificacion',
            field=models.CharField(default='V-99999999 (Consumidor Final)', max_length=50),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='productos_despachados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_bs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('PUNTO', 'Punto de Venta'), ('BIOPAGO', 'Biopago BDV'), ('CASHEA', 'Cashea'), ('PAGO_MOVIL', 'Pago Móvil Real')], default='PUNTO', max_length=50),
        ),
    ]
