# Generated by Django 6.0.4 on 2026-08-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_factura_articulos_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_negocio',
            field=models.CharField(choices=[('BODEGA', 'Bodega'), ('ROPA', 'Tienda de Ropa')], default='BODEGA', max_length=20),
        ),
    ]
