# Generated by Django 6.0.4 on 2026-08-26 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_producto_tipo_negocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255, verbose_name='Vecino / Comprador')),
                ('cedula_rif', models.CharField(max_length=20, verbose_name='Cédula o RIF')),
                ('nro_factura_origen', models.CharField(max_length=50, verbose_name='Factura Origen')),
                ('monto_deuda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Deudor ($)')),
                ('fecha_fiado', models.DateField(default=datetime.date.today)),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente / Fiar Activo'), ('MOROSO', 'Moroso / Alerta de Retraso'), ('PAGADO', 'Liquidado / Solvente')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Cuenta Por Cobrar',
                'verbose_name_plural': 'Cuentas Por Cobrar',
                'ordering': ['fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='GastoExpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Concepto del Egreso')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto en USD')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto Express',
                'verbose_name_plural': 'Gastos Express',
                'ordering': ['-fecha', '-creado_at'],
            },
        ),
    ]
