# Generated by Django 6.0.6 on 2026-08-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_cuentaporcobrar_gastoexpress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo_negocio',
        ),
    ]
